### ISSUE TITLE
[1.14.4] [28.0.13] [1.14.3-9.0.DEV.55a7af2] Upgrades not working.

### ISSUE THREAD

**Issue by maddsc17** [progwml6/ironchest#193] opened 2019-07-25 21:47 UTC
Chest upgrades are not applying to chests. I've tested different chests and different upgrades on different worlds--creative and survival, singleplayer and multiplayer. The chests do not upgrade upon right clicking them with the upgrade item, as instructed by the mod.

So the method for using the upgrades may have changed or they simply don't work.

**Comment by Tfarcenim** [comment] 2019-07-26 19:53
They don't work at all

**Comment by alexbegt** [comment] 2019-07-27 00:27
This is a forge bug; They work on 1.14.3 but in 1.14.4 the code that we used currently goes uncalled.

**Comment by Reonu** [comment] 2019-08-15 15:19
Forge released a new version (28.0.46) perhaps they fixed this?

**Comment by Nahkranoth0** [comment] 2019-08-15 21:43
Nope, i've just tested with 28.0.46 and no result

**Comment by alexbegt** [comment] 2019-08-15 23:33
Please try with 28.0.49.

**Comment by Nahkranoth0** [comment] 2019-08-16 07:25
Confirmed to be working! Thanks

Be warned that upon upgrading chest all items are expelled from chest

**Comment by alexbegt** [comment] 2019-08-16 21:06
Can you open a new bug report with a photo of this? Thank you!

**Comment by Nahkranoth0** [comment] 2019-08-17 07:00
Off course! #197 created

**Comment by alexbegt** [comment] 2019-11-21 02:07
Since the issue got fixed, I am going to close this.

**Closed as completed by alexbegt** 2019-11-21 02:07 UTC
Labels: bug, Crossmod
