### ISSUE TITLE
[1.12] My modpack (beyond the Minecraft) crashes :(

### ISSUE THREAD

**Issue by Migmag789** [progwml6/ironchest#101] opened 2017-06-21 09:45 UTC
[crash-2017-06-21_11.42.54-client.txt](https://github.com/progwml6/ironchest/files/1091085/crash-2017-06-21_11.42.54-client.txt)
Hi ! Look at this, i'm so gutted :(
Your mod is the best mod ever, why a crash ? ;(

**Comment by 61352151511** [comment] 2017-06-21 09:46
Duplicate of #98

**Comment by alexbegt** [comment] 2017-06-21 17:37
As @61352151511 Stated, this is a Duplicate of issue #98 , Closing!

**Closed as completed by alexbegt** 2017-06-21 17:37 UTC
Labels: invalid
